version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app_a
      - flask_app_b

  flask_app_a:
    build: ./flask_app_a
    container_name: flask_app_a
    ports:
      - "8000:8000"

  flask_app_b:
    build: ./flask_app_b
    container_name: flask_app_b
    ports:
      - "8001:8000"

